import type { AtlasBreadthSourceTuple } from "./claim-expansion-2026-09-atlas-breadth-shared.js";
import type { SeedClaim } from "./claims.js";
import { september2026AtlasBreadthClaim as reviewedClaim } from "./claim-expansion-2026-09-atlas-breadth-shared.js";

const earthquakeFacts = [
	"guideline",
	"Earthquake Facts & Earthquake Fantasy",
	"U.S. Geological Survey",
	2026,
	"https://www.usgs.gov/programs/earthquake-hazards/earthquake-facts-earthquake-fantasy",
	"USGS distinguishes long-term hazard assessment from exact prediction and addresses myths about animals, weather, and using small earthquakes to prevent large ones."
] as const satisfies AtlasBreadthSourceTuple;

const earlyWarningOverview = [
	"guideline",
	"Earthquake Early Warning: Overview",
	"U.S. Geological Survey",
	2026,
	"https://www.usgs.gov/programs/earthquake-hazards/science/earthquake-early-warning-overview",
	"USGS states that ShakeAlert detects an earthquake already in progress, estimates likely shaking, and can warn locations before the strongest waves arrive."
] as const satisfies AtlasBreadthSourceTuple;

const earlyWarningReview = [
	"systematic_review",
	"Earthquake early warning: Recent advances and perspectives",
	"Earth-Science Reviews",
	2020,
	"10.1016/j.earscirev.2020.103184",
	"Field review evaluates real-time source and shaking algorithms, warning uncertainty, engineering uses, and the limits imposed by detection and communication latency."
] as const satisfies AtlasBreadthSourceTuple;

const inducedEarthquakeFacts = [
	"guideline",
	"Myths and Misconceptions About Induced Earthquakes",
	"U.S. Geological Survey",
	2026,
	"https://www.usgs.gov/programs/earthquake-hazards/myths-and-misconceptions-about-induced-earthquakes",
	"USGS separates hydraulic-fracturing operations from longer and larger-volume wastewater disposal, while noting that either can trigger earthquakes in suitable geology."
] as const satisfies AtlasBreadthSourceTuple;

const inducedSeismicityAssessment = [
	"consensus_statement",
	"Induced Seismicity Potential in Energy Technologies",
	"National Research Council",
	2013,
	"10.17226/13355",
	"National Academies assessment evaluates fluid injection, withdrawal, reservoir operations, and the conditions under which energy technologies can induce felt seismicity."
] as const satisfies AtlasBreadthSourceTuple;

const tsunamiFacts = [
	"guideline",
	"What is a tsunami?",
	"NOAA National Ocean Service",
	2024,
	"https://oceanservice.noaa.gov/facts/tsunami.html",
	"NOAA defines a tsunami as a series of long waves generated by rapid water displacement and explains why oceanographers discourage the term tidal wave."
] as const satisfies AtlasBreadthSourceTuple;

const seaLevelAssessment = [
	"consensus_statement",
	"Ocean, Cryosphere and Sea Level Change",
	"Intergovernmental Panel on Climate Change",
	2023,
	"10.1017/9781009157896.011",
	"IPCC assesses global mean and regional relative sea-level change, including ocean dynamics, land-ice fingerprints, gravity, and vertical land motion."
] as const satisfies AtlasBreadthSourceTuple;

const geomagneticReview = [
	"systematic_review",
	"Deciphering records of geomagnetic reversals",
	"Reviews of Geophysics",
	2016,
	"10.1002/2015RG000506",
	"Review synthesizes paleomagnetic records and dynamo simulations, showing irregular reversal timing and substantial uncertainty about transition details."
] as const satisfies AtlasBreadthSourceTuple;

const geomagnetismIntroduction = [
	"consensus_statement",
	"Introduction to Geomagnetism",
	"U.S. Geological Survey",
	2026,
	"https://www.usgs.gov/programs/geomagnetism/introduction-geomagnetism",
	"USGS explains how convection of electrically conducting liquid in the outer core sustains Earth's main magnetic field as a self-sustaining dynamo."
] as const satisfies AtlasBreadthSourceTuple;

const groundwaterFacts = [
	"guideline",
	"What is groundwater?",
	"U.S. Geological Survey",
	2026,
	"https://www.usgs.gov/faqs/what-groundwater",
	"USGS explains that most groundwater fills connected pores and fractures in geologic materials rather than forming vast open underground rivers."
] as const satisfies AtlasBreadthSourceTuple;

export const september2026AtlasBreadthGeoscienceClaims: SeedClaim[] = [
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Does earthquake early warning predict an earthquake before it begins?",
		slug: "does-earthquake-early-warning-predict-an-earthquake-before-it-begins",
		consensusBand: "strong",
		confidenceScore: 98,
		evidenceCertainty: "high",
		bottomLine:
			"No. Earthquake early-warning systems detect a rupture after it has started and rapidly estimate where damaging shaking is heading. Because electronic messages travel faster than seismic waves, people farther from the epicenter may receive seconds to tens of seconds of warning. The system is valuable, but it is not a forecast of an earthquake hours or days in advance.",
		stableCore: [
			"Sensors first register the faster, generally less damaging P waves and estimate the event while stronger shaking propagates outward.",
			"Useful warning time depends on distance, network density, processing, telecommunications, and the growing rupture.",
			"People near the epicenter may receive little or no warning, and alerts can be late, missed, or overbroad."
		],
		openQuestions: [
			"How can systems characterize very large, evolving ruptures faster without increasing false or unnecessary alerts?",
			"Which alert designs and automated actions most reliably reduce injury and infrastructure loss?"
		],
		whatWouldChangeMinds: [
			"A validated operational system that repeatedly identifies location, time, and magnitude before any rupture signal exists.",
			"Evidence that current warnings do not depend on detecting an event already underway."
		],
		misconceptions: [
			"Early warning and earthquake prediction are different services.",
			"A phone receiving an alert before shaking does not mean the earthquake had not started.",
			"A few seconds can still support drop-cover-hold actions and automated train or valve controls."
		],
		editorSummary:
			"ShakeAlert races the shaking, not the earthquake's start. It converts rapid detection into a short protective window for locations the waves have not reached.",
		uncertaintySummary:
			"The operating principle is settled. Alert accuracy, warning time, and practical benefit vary by event geometry, location, network performance, and user response.",
		sources: [earlyWarningOverview, earlyWarningReview, earthquakeFacts]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Do frequent small earthquakes prevent a future large earthquake?",
		slug: "do-frequent-small-earthquakes-prevent-a-future-large-earthquake",
		consensusBand: "strong",
		confidenceScore: 97,
		evidenceCertainty: "high",
		bottomLine:
			"Usually no. Earthquake magnitude is logarithmic, so the many small earthquakes a region experiences release far less energy than a single large event. Small ruptures can redistribute stress locally and sometimes precede a larger rupture, but their occurrence does not safely drain an entire major fault or demonstrate that its hazard is gone.",
		stableCore: [
			"Roughly 32 magnitude-5 earthquakes release the energy of one magnitude-6 event, and about 1,000 magnitude-4 events are needed.",
			"Stress changes can either advance or delay failure on nearby fault patches.",
			"Hazard estimates rely on fault behavior and regional seismicity, not reassurance from a recent cluster of small events."
		],
		openQuestions: [
			"Which foreshock sequences contain useful information about an evolving large rupture rather than ordinary background clustering?",
			"How can short-term probability updates be communicated without presenting them as deterministic predictions?"
		],
		whatWouldChangeMinds: [
			"Prospective evidence that ordinary small-earthquake swarms reliably reduce later large-event rates below comparable fault segments.",
			"Energy and stress measurements showing routine microseismicity releases most strain accumulated on major faults."
		],
		misconceptions: [
			"Many small numbers do not add up intuitively on a logarithmic magnitude scale.",
			"A small earthquake can be a foreshock, but that label is assigned only after a larger event follows.",
			"Artificially injecting fluid to trigger small events could instead trigger damaging seismicity."
		],
		editorSummary:
			"Small earthquakes release stress on small patches, but there are not enough of them to substitute for the energy and fault area of an occasional large rupture.",
		uncertaintySummary:
			"The energy-scale argument is strong. Scientists still work on probabilistic signals within particular sequences and fault systems.",
		sources: [
			earthquakeFacts,
			[
				"consensus_statement",
				"Living on an Active Earth: Perspectives on Earthquake Science",
				"National Research Council",
				2003,
				"10.17226/10493",
				"National Academies synthesis reviews fault stress, earthquake scaling, recurrence, and why hazard cannot be eliminated by assuming small events discharge a whole fault."
			],
			earlyWarningReview
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Does hydraulic fracturing cause most induced earthquakes in oil-producing regions?",
		slug: "does-hydraulic-fracturing-cause-most-induced-earthquakes-in-oil-producing-regions",
		consensusBand: "broad",
		confidenceScore: 94,
		evidenceCertainty: "high",
		bottomLine:
			"Not in the central United States, where long-term disposal of large wastewater volumes has caused most of the recent induced-seismicity increase. Hydraulic-fracturing stages can also trigger earthquakes, and have done so in some regions, but the operations differ in volume, duration, depth, and proximity to susceptible faults. The correct attribution is site-specific, not a blanket yes or no.",
		stableCore: [
			"Raising pore pressure on a fault already near failure can reduce effective friction and trigger slip.",
			"Only a small fraction of injection wells are associated with felt earthquakes because geology and operations must align.",
			"Wastewater disposal and hydraulic fracturing should be tracked separately even when both occur in one oil and gas field."
		],
		openQuestions: [
			"Which combinations of injection rate, cumulative volume, fault connectivity, and stress best forecast damaging induced events?",
			"How quickly does hazard decline after operators reduce or stop injection in different geologic settings?"
		],
		whatWouldChangeMinds: [
			"Regional well and seismic records showing fracturing stages, rather than disposal, explain most induced events after exposure is modeled correctly.",
			"Mechanistic evidence that wastewater pressure cannot reach or destabilize implicated faults."
		],
		misconceptions: [
			"Wastewater is produced by conventional wells as well as hydraulically fractured wells.",
			"Most disposal wells do not cause felt earthquakes, but a minority can create serious hazard.",
			"Natural and induced earthquakes use the same fault-slip physics and can be difficult to classify event by event."
		],
		editorSummary:
			"Fluid injection can induce earthquakes, but the dominant operation in many U.S. sequences has been wastewater disposal rather than the brief rock-fracturing stage itself.",
		uncertaintySummary:
			"The mechanism and regional associations are well supported. Attribution and maximum-magnitude risk remain specific to local faults, pressure pathways, and operating history.",
		sources: [inducedEarthquakeFacts, inducedSeismicityAssessment, [
			"consensus_statement",
			"Induced Seismicity Strategic Vision",
			"U.S. Geological Survey",
			2023,
			"https://pubs.usgs.gov/circ/1509/circ1509.pdf",
			"USGS research strategy synthesizes observations, hazard modeling, operational data gaps, and mitigation priorities for injection-induced earthquakes."
		]]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Can unusual animal behavior reliably predict earthquakes?",
		slug: "can-unusual-animal-behavior-reliably-predict-earthquakes",
		consensusBand: "strong",
		confidenceScore: 95,
		evidenceCertainty: "moderate",
		bottomLine:
			"No reliable predictive method has been demonstrated. Animals can detect weak shaking or other cues before nearby people notice them, but reports of unusual behavior are usually collected after an earthquake, lack a defined baseline, and rarely make prospective predictions with a location, time window, and magnitude. False alarms and ordinary behavioral variation are central problems.",
		stableCore: [
			"A useful prediction must be specified before the event and tested against both hits and false alarms.",
			"Many species respond to immediate P waves, sound, or ground motion seconds before humans perceive stronger shaking.",
			"Retrospective anecdotes cannot establish sensitivity or specificity."
		],
		openQuestions: [
			"Do any species respond reproducibly to measurable pre-rupture signals under controlled prospective monitoring?",
			"Can dense animal-sensor networks add information beyond ordinary geophysical instruments after accounting for false alarms?"
		],
		whatWouldChangeMinds: [
			"Preregistered, replicated trials in which a defined behavior predicts earthquake time, place, and size substantially better than chance.",
			"A measured pre-rupture physical cue and demonstrated sensory pathway explaining the predictive lead time."
		],
		misconceptions: [
			"An animal reacting seconds before a person is not necessarily predicting a rupture before it starts.",
			"Remembering odd behavior before a rare disaster while forgetting uneventful odd behavior creates hindsight bias.",
			"Lack of a reliable animal predictor does not mean animals have no sensitive hearing or vibration detection."
		],
		editorSummary:
			"Animals may notice an earthquake's earliest physical signals before people do, but that is not a validated days-ahead forecasting system.",
		uncertaintySummary:
			"Available studies do not support operational prediction. Standardized, prospective monitoring could still test narrower species and signal hypotheses.",
		sources: [
			earthquakeFacts,
			[
				"systematic_review",
				"Review: Can Animals Predict Earthquakes?",
				"Bulletin of the Seismological Society of America",
				2018,
				"10.1785/0120170313",
				"Review finds pervasive retrospective reporting, weak baselines, short observation windows, and insufficient evidence for reproducible animal prediction."
			],
			earlyWarningOverview
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Are tsunamis simply unusually large tides?",
		slug: "are-tsunamis-simply-unusually-large-tides",
		consensusBand: "strong",
		confidenceScore: 99,
		evidenceCertainty: "high",
		bottomLine:
			"No. Tides are predictable water-level changes driven mainly by the Moon's and Sun's gravity. A tsunami is a series of long waves created by sudden displacement of water, most often from an undersea earthquake but sometimes from landslides, volcanic activity, or impacts. Local tide level can worsen or reduce inundation, but it does not generate the tsunami.",
		stableCore: [
			"In deep ocean a tsunami can be low in height, extremely long in wavelength, and fast-moving.",
			"As the wave enters shallow water it slows, compresses, and can rise or surge far inland.",
			"The first wave may not be the largest, and dangerous currents can continue for hours."
		],
		openQuestions: [
			"How can source inversions and offshore sensors improve local arrival and inundation forecasts in real time?",
			"Which warning formats produce the fastest evacuation without causing people to return after the first wave?"
		],
		whatWouldChangeMinds: [
			"Measurements showing tsunami generation follows astronomical tidal forcing rather than abrupt water displacement.",
			"A wave model that explains observed arrival times and runup using ordinary tidal periods and amplitudes."
		],
		misconceptions: [
			"Tidal wave is an entrenched phrase but a misleading scientific name.",
			"A tsunami does not always arrive as a breaking wall of water; it may look like a rapidly rising flood or powerful current.",
			"A small wave offshore can still become destructive at the coast."
		],
		editorSummary:
			"Tides and tsunamis can overlap at the shoreline, but they have different causes, periods, and warning systems.",
		uncertaintySummary:
			"The physical distinction is settled. The difficult part is forecasting the local consequences of a particular source and coastline quickly enough for evacuation.",
		sources: [
			tsunamiFacts,
			[
				"consensus_statement",
				"Tsunami Warning and Preparedness: An Assessment of the U.S. Tsunami Program and the Nation's Preparedness Efforts",
				"National Research Council",
				2011,
				"10.17226/12628",
				"National Academies assessment covers tsunami generation, detection, forecast, warning, and evacuation as distinct from astronomical tides."
			],
			[
				"guideline",
				"JetStream: Tsunamis",
				"NOAA National Weather Service",
				2025,
				"https://www.noaa.gov/jetstream/tsunamis",
				"NOAA training explains deep-water propagation, coastal amplification, natural warning signs, and why a tsunami is a wave series rather than a tide."
			]
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Is sea level the same height and trend everywhere?",
		slug: "is-sea-level-the-same-height-and-trend-everywhere",
		consensusBand: "strong",
		confidenceScore: 98,
		evidenceCertainty: "high",
		bottomLine:
			"No. Global mean sea level summarizes the average ocean-volume change, while regional and relative sea level vary with currents, winds, temperature, salinity, gravity, ice loss, and whether the land itself is rising or sinking. A coast can therefore experience a faster, slower, or temporarily different trend than the global average without contradicting global sea-level rise.",
		stableCore: [
			"Tide gauges measure the ocean relative to local land; satellites estimate sea-surface height in a global reference frame.",
			"Land subsidence can amplify local relative rise, while post-glacial uplift can offset or reverse it.",
			"Melting ice sheets alter gravity and Earth's rotation, producing distinct regional sea-level fingerprints."
		],
		openQuestions: [
			"How will ice-sheet dynamics, ocean circulation, and vertical land motion combine at individual coastlines this century?",
			"How can local observations and projections better capture compound flooding from tides, storms, rivers, and groundwater?"
		],
		whatWouldChangeMinds: [
			"Global geodetic and tide-gauge records showing no spatial variation despite measured land motion and ocean dynamics.",
			"A physical model in which mass redistribution, temperature, currents, and crustal motion cannot affect relative sea level."
		],
		misconceptions: [
			"Sea level is a gravitational and dynamical surface, not a rigid bathtub line.",
			"A falling local tide-gauge trend does not by itself refute a rising global mean.",
			"Local planning needs relative sea level and extremes, not only the global average."
		],
		editorSummary:
			"There is one useful global average and many locally experienced sea levels. Both are real measurements answering different questions.",
		uncertaintySummary:
			"Spatial variation is well established. Local projections carry wider uncertainty from ice sheets, ocean circulation, storm behavior, and vertical land motion.",
		sources: [
			seaLevelAssessment,
			[
				"consensus_statement",
				"Sea Level Trends and Extremes",
				"NOAA Center for Operational Oceanographic Products and Services",
				2026,
				"https://tidesandcurrents.noaa.gov/trends-and-extremes/",
				"NOAA separates global, regional, and relative sea level and maps how vertical land motion and ocean processes produce different local trends."
			],
			[
				"guideline",
				"NASA Sea Level Change Portal",
				"NASA Sea Level Change Team",
				2026,
				"https://sealevel.nasa.gov/",
				"NASA integrates satellite, tide-gauge, ocean-heat, land-ice, and regional-fingerprint evidence for sea-level change."
			]
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Is Earth's magnetic field reversal overdue and predictably catastrophic?",
		slug: "is-earths-magnetic-field-reversal-overdue-and-predictably-catastrophic",
		consensusBand: "broad",
		confidenceScore: 94,
		evidenceCertainty: "moderate",
		bottomLine:
			"No. Geomagnetic reversals recur irregularly, so the 780,000 years since the last full reversal is not a missed schedule. The field would likely weaken and become more complex over centuries to millennia, which could increase satellite and radiation-management challenges. The geological record does not establish that reversals routinely cause mass extinctions or sudden planetary catastrophe.",
		stableCore: [
			"Rocks preserve many past polarity reversals with highly variable intervals between them.",
			"The current field changes and weakens in some regions, but that alone does not demonstrate an imminent reversal.",
			"A reversal changes magnetic polarity, not Earth's geographic rotation axis."
		],
		openQuestions: [
			"What field geometry, duration, and minimum intensity would characterize the next transition?",
			"How vulnerable would modern satellites, navigation, aviation, and power systems be under particular weakened-field scenarios?"
		],
		whatWouldChangeMinds: [
			"A robust periodic law that prospectively predicts reversal timing from paleomagnetic records.",
			"Consistent stratigraphic evidence linking reversals themselves to abrupt global biological catastrophe after other causes are excluded."
		],
		misconceptions: [
			"Average interval is not a countdown clock.",
			"Magnetic north moving is not the same event as a completed polarity reversal.",
			"Reduced shielding would not mean the magnetic field instantly disappears everywhere."
		],
		editorSummary:
			"Earth's field has reversed many times, but not on a timetable. A future transition deserves infrastructure study, not claims of a scheduled apocalypse.",
		uncertaintySummary:
			"Past reversals are secure in the rock record. Their exact mechanism, next timing, transition geometry, and consequences for technological society remain uncertain.",
		sources: [
			geomagneticReview,
			[
				"landmark_study",
				"Earth's magnetic field is probably not reversing",
				"Proceedings of the National Academy of Sciences",
				2018,
				"10.1073/pnas.1722110115",
				"Comparison with paleomagnetic analogues finds that recent field changes do not uniquely resemble an imminent excursion or reversal."
			],
			geomagnetismIntroduction
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Are shifting magnetic poles causing today's climate change?",
		slug: "are-shifting-magnetic-poles-causing-todays-climate-change",
		consensusBand: "strong",
		confidenceScore: 98,
		evidenceCertainty: "high",
		bottomLine:
			"No. Earth's magnetic field and pole locations change, but the energy involved in near-Earth electromagnetic processes is far too small and too high in the atmosphere to explain modern surface warming. There is no known mechanism or observed fingerprint matching current climate change, while greenhouse forcing predicts the measured energy imbalance and temperature pattern.",
		stableCore: [
			"Magnetic variation strongly affects space weather and charged particles, not the lower atmosphere's dominant heat budget.",
			"Past reversals are not consistently paired with major climate disruption in paleoclimate records.",
			"The geographic poles, magnetic poles, and planet's rotational axis are different concepts."
		],
		openQuestions: [
			"How do solar and geomagnetic conditions affect the upper atmosphere and technological systems during extreme space-weather events?",
			"What small regional or upper-atmosphere couplings can be detected without confusing them with the cause of global surface warming?"
		],
		whatWouldChangeMinds: [
			"A quantified magnetic-to-climate mechanism supplying the observed lower-atmosphere energy imbalance and temperature fingerprints.",
			"Long-term records showing global surface temperature follows geomagnetic forcing better than greenhouse and known natural drivers."
		],
		misconceptions: [
			"A real change in magnetic north does not make it the cause of every simultaneous Earth-system trend.",
			"Magnetic shielding and greenhouse infrared absorption act through different physics.",
			"Solar storms can disrupt technology without producing the observed century-scale climate trend."
		],
		editorSummary:
			"Pole drift is real, but it lacks the energy pathway and observational fingerprints needed to explain present warming.",
		uncertaintySummary:
			"The conclusion about current global warming is strong. Research continues on much smaller upper-atmosphere and space-weather interactions.",
		sources: [
			[
				"consensus_statement",
				"Flip Flop: Why Variations in Earth's Magnetic Field Aren't Causing Today's Climate Change",
				"NASA Science",
				2021,
				"https://science.nasa.gov/science-research/earth-science/flip-flop-why-variations-in-earths-magnetic-field-arent-causing-todays-climate-change/",
				"NASA compares upper-atmosphere magnetic energy with the surface climate budget and finds no viable mechanism for present warming."
			],
			geomagneticReview,
			geomagnetismIntroduction
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Is most groundwater stored in vast underground lakes and rivers?",
		slug: "is-most-groundwater-stored-in-vast-underground-lakes-and-rivers",
		consensusBand: "strong",
		confidenceScore: 98,
		evidenceCertainty: "high",
		bottomLine:
			"No. Most groundwater occupies pores between grains and cracks or fractures in rock, more like water in a sponge than a hidden open lake. It moves through connected spaces, often slowly. Large underground channels do occur in karst landscapes and lava tubes, but they are special geologic settings rather than the usual structure of an aquifer.",
		stableCore: [
			"An aquifer is permeable material that stores and transmits useful quantities of water.",
			"Porosity controls storage, while connected permeability controls how readily water can flow to wells and springs.",
			"Pumping can lower water tables, reduce streamflow, cause land subsidence, or draw contaminants even when no visible cavity exists."
		],
		openQuestions: [
			"How quickly do particular aquifers recharge under changing rainfall, land cover, and pumping?",
			"How can fractured-rock and karst flow paths be mapped well enough to predict contamination and sustainable yield?"
		],
		whatWouldChangeMinds: [
			"Borehole, geophysical, and tracer evidence showing open channels dominate storage across ordinary sand, gravel, and fractured-rock aquifers.",
			"Regional water-balance measurements incompatible with pore and fracture storage."
		],
		misconceptions: [
			"The water table is not the roof of a universal hollow chamber.",
			"Artesian water rises because a confined aquifer is pressurized, not because a hidden river pushes it upward.",
			"Caves can contain streams without representing how most groundwater is stored."
		],
		editorSummary:
			"Groundwater is usually water within rock and sediment, not water beneath rock in a giant cavity. That distinction matters for recharge, pumping, and pollution.",
		uncertaintySummary:
			"The general pore-and-fracture model is basic hydrogeology. Storage and flow pathways can still be highly uncertain in a specific aquifer.",
		sources: [
			groundwaterFacts,
			[
				"guideline",
				"The Hydrology of Groundwater",
				"U.S. Geological Survey",
				2017,
				"https://md.water.usgs.gov/preview/faq/groundwater.html",
				"USGS uses the sponge analogy to explain connected pores, fractures, aquifer recharge, flow, and pumping effects."
			],
			[
				"consensus_statement",
				"Ground Water and Surface Water: A Single Resource",
				"U.S. Geological Survey",
				1998,
				"https://pubs.usgs.gov/circ/circ1139/",
				"USGS synthesis describes groundwater storage and its hydraulic connection to streams, wetlands, and pumping."
			]
		]
	}),
	reviewedClaim({
		topicSlug: "earth-and-geoscience",
		title: "Is Earth's main magnetic field generated by a permanent solid magnet in the core?",
		slug: "is-earths-main-magnetic-field-generated-by-a-permanent-solid-magnet-in-the-core",
		consensusBand: "strong",
		confidenceScore: 98,
		evidenceCertainty: "high",
		bottomLine:
			"No. Earth's main field is generated by a geodynamo: moving, electrically conducting liquid iron alloy in the outer core induces electric currents that sustain a changing magnetic field. Core temperatures are too high for iron to behave like an ordinary permanent bar magnet. The solid inner core and planetary rotation help shape the energy and flow, but the active generator is the convecting outer core.",
		stableCore: [
			"Seismic waves show a liquid outer core surrounding a solid inner core.",
			"Thermal and compositional buoyancy drive conducting fluid motion, while induction links that motion to magnetic fields.",
			"Secular variation and reversals are expected features of a dynamic dynamo rather than failures of a fixed magnet."
		],
		openQuestions: [
			"How do inner-core growth, heat flow across the core-mantle boundary, and small-scale turbulence control field behavior?",
			"Which observations can best forecast decadal secular variation without implying deterministic reversal prediction?"
		],
		whatWouldChangeMinds: [
			"Seismic and mineral-physics evidence showing a cool ferromagnetic permanent magnet can exist at core conditions.",
			"A non-dynamo model that explains field strength, geometry, secular variation, and reversals more accurately."
		],
		misconceptions: [
			"Iron composition alone does not make a hot planetary core a bar magnet.",
			"The inner core is solid, but most field generation occurs in the liquid outer core.",
			"Magnetic north moving is expected because the field is dynamic."
		],
		editorSummary:
			"Earth's magnetic field is continuously generated by moving conductive fluid. It is a planetary electrical dynamo, not a buried refrigerator magnet.",
		uncertaintySummary:
			"The geodynamo framework is strongly supported. Fine-scale core flow, energy history, and reversal dynamics remain difficult to observe directly.",
		sources: [
			geomagnetismIntroduction,
			[
				"guideline",
				"How does the Earth's core generate a magnetic field?",
				"U.S. Geological Survey",
				2022,
				"https://www.usgs.gov/faqs/how-does-earths-core-generate-a-magnetic-field",
				"USGS gives a concise account of turbulent outer-core convection, electromagnetic induction, and self-sustaining field generation."
			],
			[
				"consensus_statement",
				"The Interior of the Earth",
				"U.S. Geological Survey",
				2025,
				"https://pubs.usgs.gov/gip/interior/",
				"USGS integrates seismic waves, planetary inertia, dynamo theory, and mineral physics to distinguish the liquid outer and solid inner core."
			]
		]
	})
];
