import type { ReadingGuideContent } from "./types";

export const floodGroundwaterGuide: ReadingGuideContent = {
	takeaway:
		"A water headline can confuse a probability with a timetable, a level with a flow, or stored water with a renewable supply. Identify the quantity, connected system and time scale before drawing the stronger conclusion.",
	scope: "An educational guide to flood and groundwater claims, source-checked October 5, 2026 UTC. It is not a current warning, property-risk assessment, drinking-water certificate, well-design manual or emergency instruction. Original institutional explanations and one original paper abstract were checked; independent expert review has not been completed.",
	sections: [
		{
			id: "probability-not-calendar",
			title: "1. A return period is not an appointment",
			paragraphs: [
				{
					text: "A hundred-year flood label describes an estimated annual chance of exceeding a specified flood magnitude. It does not reserve one event for each century. A flood this year therefore does not start a guaranteed quiet interval. The threshold and the estimate belong to a particular place and dataset, not to all rivers or every property. Before interpreting a headline, identify the variable and location to which its probability applies.",
					sources: ["flood"]
				},
				{
					text: "The useful follow-up is how the estimate was obtained and whether its assumptions still fit. A limited observation record and changing catchment conditions can affect the result. Several events close together do not automatically refute the probability definition, while a long quiet interval does not establish immunity. This guide makes no repeated-year calculation for a property: such a calculation would require explicit assumptions about how annual probabilities and dependence behave through time.",
					sources: ["flood", "hazards"]
				}
			]
		},
		{
			id: "height-versus-flow",
			title: "2. A water level is not a universal flow meter",
			paragraphs: [
				{
					text: "River stage measures height relative to a reference; discharge measures volume passing per unit time. USGS explains how observations of flow establish a station's rating relation. That is a local calibration, not a conversion valid for every river. The same visible height in two channels can correspond to different discharge. When two reports appear to disagree, first check that their quantities, reference points and locations actually match.",
					sources: ["stream"]
				},
				{
					text: "Channel conditions also change. Erosion, deposition, debris and ice can affect the relation, so a rating needs maintenance rather than unquestioning reuse. A river photograph records a scene, not all the information needed for a calibrated discharge. A flood threshold expressed as flow should not silently become the same numerical threshold expressed as height. None of these distinctions makes a gauge useless; they explain what its number does and does not directly observe.",
					sources: ["stream", "flood"]
				}
			]
		},
		{
			id: "connected-catchment",
			title: "3. The water system is larger than the sky overhead",
			paragraphs: [
				{
					text: "NWS describes floods generated by upstream rain as well as snowmelt and river-ice effects. A locally clear sky can coexist with water moving into the area from elsewhere. A rain gauge at the flooded location is not a complete basin observation. The relevant question is which inputs and pathways produced the high water, over what period. This is a mechanism explanation, not evidence that any named river is currently flooding.",
					sources: ["hazards"]
				},
				{
					text: "The same connected-system reasoning helps interpret groundwater exchange. A gaining stream receives groundwater; a losing stream sends water into the ground. One river can have both kinds of reach, and the relation can change with conditions. A diagram of baseflow therefore illustrates one direction, not a permanent rule for every river. Ask where and when an exchange statement applies, and whether the local hydraulic connection has actually been established.",
					sources: ["exchange", "interaction"]
				}
			]
		},
		{
			id: "rain-is-not-recovery",
			title: "4. Rain, infiltration and recharge are different steps",
			paragraphs: [
				{
					text: "A wet season is not a direct measure of replenishment at every depth. Rain can run off, return to the atmosphere or enter pathways that do not quickly reach the aquifer being discussed. USGS's groundwater-flow illustrations show differing routes and time scales, not one refill clock. A headline about wet soil, a rising shallow well and a recovered deep resource may be describing three different outcomes. Do not join them into one claim without evidence.",
					sources: ["flow", "aquifer"]
				},
				{
					text: "Recovery also concerns the continuing balance between inputs and withdrawals. A local response can be real while a broader supply remains limited. To establish basin recovery requires appropriate observations and an applicable water balance, not only a recent rainfall total. Historical figures and conceptual travel times are not adopted here as current measurements. The linked review explains the distinction without forecasting a drought, setting a pumping allowance or certifying a resource's future availability.",
					sources: ["flow", "storage"]
				}
			]
		},
		{
			id: "storage-versus-transmission",
			title: "5. Holding water is not the same as supplying it",
			paragraphs: [
				{
					text: "Porosity and permeability answer different questions. The first concerns pore space; the second concerns transmission through connected paths. A water-bearing material can have storage without delivering water readily to a well. A claim about a large underground volume should therefore not quietly become a claim about a sustained delivery rate. The familiar sponge picture can teach storage while hiding the need to understand the actual geologic formation and its connected pathways.",
					sources: ["storage", "aquifer"]
				},
				{
					text: "Artesian terminology adds another distinction: hydraulic head can raise water in a well above the top of a confined aquifer without raising it above the ground or outlet. Only the latter condition produces a flowing artesian well. Depth alone is not the definition. Neither artesian pressure nor surface flow establishes purity, a permanent yield or limitless supply. A diagram needs its aquifer and elevation references before the word pressure can be interpreted properly.",
					sources: ["artesian"]
				}
			]
		},
		{
			id: "withdrawals-and-outlets",
			title: "6. A withdrawal can affect another part of the system",
			paragraphs: [
				{
					text: "Pumping from a connected aquifer can reduce water that would otherwise discharge to a stream or induce stream water to enter the aquifer. A pump need not sit in the river to matter. Location and timing depend on the system and pumping history. Leake and colleagues' original abstract describes a capture-mapping method with basin examples. It does not provide one fraction to apply to every well, and this guide has not reproduced its model calculations.",
					sources: ["depletion", "capture"]
				},
				{
					text: "A spring is another outlet, not a device that creates new water. USGS identifies recharge, head, geology and nearby withdrawals as influences on discharge. Some springs are intermittent and others persistent, but a visit does not establish a perpetual water budget. This physical explanation is separate from drinking-water quality: clear, naturally emerging water is not a certificate of safety. No spring was tested, monitored or modified in preparing this guide.",
					sources: ["spring", "interaction"]
				}
			]
		},
		{
			id: "bounded-protection",
			title: "7. Risk reduction is valuable without being absolute",
			paragraphs: [
				{
					text: "USACE describes levees as systems that reduce flooding frequency and explicitly retains residual risk. Protection is a bounded claim about a system and events, not proof that no water can ever enter the area. Recognizing this limitation does not imply levees have no benefit. It prevents a relative improvement from becoming a zero-risk promise. Generic explanations cannot certify the present condition of an individual system or establish a particular property's legal or insurance status.",
					sources: ["levee", "levee-history"]
				},
				{
					text: "Use a consistent reading checklist across these claims: what quantity was observed, where, when, by which method, and what additional inference was made? Agency explanations are useful technical references, not formal votes of scientists. Several USGS pages can describe the same framework rather than independent datasets. The cited capture paper was checked at abstract and DOI-metadata level; its full disclosures and analysis were not audited. The uncertainty belongs with the conclusion, not hidden behind an impressive water image.",
					sources: ["capture", "stream", "levee"]
				}
			]
		}
	],
	questions: [
		"Is this a probability, a measured height, a flow rate or a stored volume?",
		"Which catchment, aquifer, depth and period does it concern?",
		"Is the source defining a mechanism or estimating a local outcome?",
		"What observations would support the stronger recovery or protection claim?",
		"Are several agency pages describing one framework rather than independent datasets?"
	],
	sources: [
		{
			id: "flood",
			title: "The 100-Year Flood",
			url: "https://www.usgs.gov/water-science-school/science/100-year-flood",
			kind: "Technical reference",
			note: "Original USGS annual-probability explanation checked; no local risk estimate or stationary-process guarantee inferred."
		},
		{
			id: "stream",
			title: "How Streamflow is Measured",
			url: "https://www.usgs.gov/water-science-school/science/how-streamflow-measured",
			kind: "Technical reference",
			note: "Original rating-maintenance explanation checked; historical station counts not reused as current."
		},
		{
			id: "hazards",
			title: "Flood Related Hazards",
			url: "https://www.weather.gov/safety/flood-hazards",
			kind: "Technical reference",
			note: "Original NWS upstream and non-rainfall mechanisms checked, not a current local warning or casualty-rate claim."
		},
		{
			id: "exchange",
			title: "Rivers Contain Groundwater",
			url: "https://www.usgs.gov/special-topics/water-science-school/science/rivers-contain-groundwater",
			kind: "Technical reference",
			note: "Original gaining and losing reach explanation checked; schematic not treated as a measured basin balance."
		},
		{
			id: "interaction",
			title: "Groundwater and Surface-Water Interactions",
			url: "https://water.usgs.gov/ogw/gwsw.html",
			kind: "Institutional overview",
			note: "Original USGS connected-resource framework checked; same agency as detailed resources, not an independent dataset."
		},
		{
			id: "flow",
			title: "Groundwater Flow and the Water Cycle",
			url: "https://www.usgs.gov/index.php/special-topics/water-science-school/science/groundwater-flow-and-water-cycle",
			kind: "Technical reference",
			note: "Original pathways explanation checked; diagram travel times are conceptual rather than site-specific refill predictions."
		},
		{
			id: "aquifer",
			title: "Aquifers and Groundwater",
			url: "https://www.usgs.gov/water-science-school/science/aquifers-and-groundwater",
			kind: "Technical reference",
			note: "Original recharge, permeability and confinement explanation checked through the reader; no yield certification."
		},
		{
			id: "storage",
			title: "Groundwater Storage and the Water Cycle",
			url: "https://www.usgs.gov/water-science-school/science/groundwater-storage-and-water-cycle",
			kind: "Technical reference",
			note: "Original storage and transmission distinctions checked; historical global-volume tables not adopted as current."
		},
		{
			id: "artesian",
			title: "Artesian Water and Artesian Wells",
			url: "https://www.usgs.gov/water-science-school/science/artesian-water-and-artesian-wells",
			kind: "Technical reference",
			note: "Original flowing-well distinction checked; hydraulic head retained without a rock-weight-only story or construction advice."
		},
		{
			id: "depletion",
			title: "Groundwater Decline and Depletion",
			url: "https://www.usgs.gov/water-science-school/science/groundwater-decline-and-depletion",
			kind: "Technical reference",
			note: "Original connected-stream mechanism checked through the reader; no global or local depletion rate generalized."
		},
		{
			id: "capture",
			title: "A New Capture Fraction Method to Map How Pumpage Affects Surface Water Flow",
			url: "https://www.usgs.gov/publications/a-new-capture-fraction-method-map-how-pumpage-affects-surface-water-flow",
			kind: "Original research abstract, 2010",
			note: "USGS abstract, Consensus record and DOI 10.1111/j.1745-6584.2010.00701.x checked; full paper, acknowledgements and raw data not audited."
		},
		{
			id: "spring",
			title: "Springs and the Water Cycle",
			url: "https://www.usgs.gov/water-science-school/science/springs-and-water-cycle?page=1",
			kind: "Technical reference",
			note: "Original flow influences checked; no perpetual resource estimate or drinking-water endorsement inferred."
		},
		{
			id: "levee",
			title: "What is a Levee?",
			url: "https://levees.sec.usace.army.mil/levee-basics/what-is-a-levee/",
			kind: "Technical reference",
			note: "Original USACE definition and residual-risk framing checked; no system-specific assessment or intervention instructions."
		},
		{
			id: "levee-history",
			title: "History of Levees",
			url: "https://levees.sec.usace.army.mil/levee-basics/history-of-levees/",
			kind: "Institutional overview",
			note: "Same USACE program as the definition; historical discussion is not an independent current levee certification."
		}
	]
};
